-- MySQL Script generated by MySQL Workbench
-- 07/24/16 14:45:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema innebandy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `innebandy` ;

-- -----------------------------------------------------
-- Schema innebandy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `innebandy` DEFAULT CHARACTER SET utf8 ;
USE `innebandy` ;

-- -----------------------------------------------------
-- Table `innebandy`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innebandy`.`users` ;

CREATE TABLE IF NOT EXISTS `innebandy`.`users` (
  `email` VARCHAR(80) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `enabled` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innebandy`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innebandy`.`user_roles` ;

CREATE TABLE IF NOT EXISTS `innebandy`.`user_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(80) NOT NULL,
  `role` ENUM('USER', 'ADMIN') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_roles_users1_idx` (`email` ASC),
  CONSTRAINT `fk_user_roles_users1`
    FOREIGN KEY (`email`)
    REFERENCES `innebandy`.`users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innebandy`.`attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innebandy`.`attendance` ;

CREATE TABLE IF NOT EXISTS `innebandy`.`attendance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(80) NOT NULL,
  `date` DATETIME NOT NULL,
  `type` ENUM('ATTEND', 'NOT_ATTEND', 'NOT_DECIDED') NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_date_unique_idx` (`email` ASC, `date` ASC),
  INDEX `fk_attendance_users1_idx` (`email` ASC),
  CONSTRAINT `fk_attendance_users1`
    FOREIGN KEY (`email`)
    REFERENCES `innebandy`.`users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
