(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['attendanceResult'] = template({"1":function(container,depth0,helpers,partials,data) {
    return "";
},"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, alias1=depth0 != null ? depth0 : {}, alias2=helpers.helperMissing;

  return "<div class=\"row\">\r\n    <div class=\"col-sm-12\">\r\n        <div class=\"jumbotron jumbotron-"
    + ((stack1 = (helpers.severity || (depth0 && depth0.severity) || alias2).call(alias1,depth0,{"name":"severity","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + "\">\r\n            <h2><small>Trening 25. juni 2016</small></h2>\r\n            <h1 class=\"jumbotron-header-"
    + ((stack1 = (helpers.severity || (depth0 && depth0.severity) || alias2).call(alias1,depth0,{"name":"severity","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + "\">THE GAME IS ON!</h1>\r\n        </div>\r\n    </div>\r\n</div>\r\n<div class=\"row\">\r\n    <div class=\"col-sm-7\">\r\n        <div class=\"panel panel-default blue-box\">\r\n            <div class=\"panel-body\">\r\n                <h3>Kommer du på trening i dag?</h3>\r\n                <form>\r\n                    <div class=\"form-group\">\r\n                        <select class=\"form-control\" style=\"padding:5px;font-size: 120%;\">\r\n                            <option></option>\r\n                            <option>Jeg kommer</option>\r\n                            <option>Jeg kommer ikke</option>\r\n                        </select>\r\n                    </div>\r\n                </form>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div class=\"col-sm-5\">\r\n        <div class=\"panel panel-default yellow-box\">\r\n            <div class=\"panel-body\">\r\n                <p>\r\n                    Trening hver tirsdag fra kl 20.00 til kl 22.00 i <a href=\"https://www.google.no/maps/place/Gaustadhallen/@59.2659743,10.7717805,15z/data=!4m5!3m4!1s0x0:0xe28d42b4c8661585!8m2!3d59.2659743!4d10.7717805\">Gaustadhallen</a>\r\n                </p>\r\n                <p>\r\n                    Prisen er kr 150,- per måned<br>\r\n                    Betal med <a href=\"https://www.vipps.no/sos.html\">Vipps</a> til 91193609\r\n                </p>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n<div class=\"row\">\r\n    <div class=\"col-sm-4\">\r\n        <div class=\"panel panel-default green-box\">\r\n            <div class=\"panel-body\">\r\n                <table><tr><td>KOMMER&nbsp;</td><td><div class=\"mybadge\">3</div></td></tr></table>\r\n                <hr>\r\n                Steinar<br>\r\n                Lars-Petter<br>\r\n                Fredrik\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div class=\"col-sm-4\">\r\n        <div class=\"panel panel-default gray-box\">\r\n            <div class=\"panel-body\">\r\n                <table><tr><td>KOMMER IKKE&nbsp;</td><td><div class=\"mybadge\">4</div></td></tr></table>\r\n                <hr>\r\n                Steinar<br>\r\n                Lars-Petter\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div class=\"col-sm-4\">\r\n        <div class=\"panel panel-default gray-box\">\r\n            <div class=\"panel-body\">\r\n                <table><tr><td>IKKE SVART&nbsp;</td><td><div class=\"mybadge\">4</div></td></tr></table>\r\n                <hr>\r\n                Steinar<br>\r\n                Lars-Petter\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n";
},"useData":true});
templates['login'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div id=\"login\">\r\n    <form id=\"loginform\">\r\n        <fieldset class=\"form-group\">\r\n            <label for=\"email\">Epost</label>\r\n            <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"Epost\">\r\n        </fieldset>\r\n        <fieldset class=\"form-group\">\r\n            <label for=\"pwd\">Passord</label>\r\n            <input type=\"password\" class=\"form-control\" id=\"pwd\" placeholder=\"Passord\">\r\n        </fieldset>\r\n        <button type=\"submit\" id=\"btnLogin\" class=\"btn btn-primary\">OK</button>\r\n    </form>\r\n</div>\r\n";
},"useData":true});
})();