(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['activity'] = template({"1":function(container,depth0,helpers,partials,data) {
    return "                    <hr>\r\n";
},"3":function(container,depth0,helpers,partials,data) {
    return " selected";
},"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, helper, alias1=depth0 != null ? depth0 : {}, alias2=helpers.helperMissing, alias3="function", alias4=container.escapeExpression, alias5=container.lambda;

  return "<div id=\"activity-row-"
    + alias4(((helper = (helper = helpers.id || (depth0 != null ? depth0.id : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"id","hash":{},"data":data}) : helper)))
    + "\" data-id=\""
    + alias4(((helper = (helper = helpers.id || (depth0 != null ? depth0.id : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"id","hash":{},"data":data}) : helper)))
    + "\" class=\"row makeMeDraggable makeMeDroppable\">\r\n    <div class=\"col-sm-12\">\r\n        <div id=\"activity-"
    + alias4(((helper = (helper = helpers.id || (depth0 != null ? depth0.id : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"id","hash":{},"data":data}) : helper)))
    + "\" class=\"activity\">\r\n            <div class=\"tablebox\">\r\n                <div class=\"row\" style=\"vertical-align: middle;\">\r\n                    <div class=\"col-xs-10\">\r\n                        "
    + alias4(alias5(((stack1 = (depth0 != null ? depth0.activityType : depth0)) != null ? stack1.name : stack1), depth0))
    + " &nbsp;&nbsp;<b>"
    + alias4(alias5(((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1), depth0))
    + "</b>&nbsp;timer&nbsp;<b>"
    + alias4(alias5(((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.minutes : stack1), depth0))
    + "</b>&nbsp;min\r\n                    </div>\r\n                    <div class=\"col-xs-2\">\r\n                        <div class=\"pull-right\">\r\n                            <table>\r\n                                <tr>\r\n                                    <td style=\"padding-right:10px;\">\r\n                                        <a href=\"#\" class=\"move-activity\" data-id=\""
    + alias4(((helper = (helper = helpers.id || (depth0 != null ? depth0.id : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"id","hash":{},"data":data}) : helper)))
    + "\" data-url=\"/treg/activity/move?id="
    + alias4(((helper = (helper = helpers.id || (depth0 != null ? depth0.id : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"id","hash":{},"data":data}) : helper)))
    + "\">\r\n                                            <i class=\"glyphicon glyphicon-share-alt\" style=\"font-size: 20px;\"></i>\r\n                                        </a>\r\n                                    </td>\r\n                                    <td style=\"padding-right:10px;\">\r\n                                        <a href=\"#\" class=\"edit-activity\" data-id=\""
    + alias4(((helper = (helper = helpers.id || (depth0 != null ? depth0.id : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"id","hash":{},"data":data}) : helper)))
    + "\">\r\n                                            <i class=\"glyphicon glyphicon-edit\" style=\"font-size: 20px;\"></i>\r\n                                        </a>\r\n                                    </td>\r\n                                    <td>\r\n                                        <a href=\"#\" class=\"delete-activity\" data-id=\""
    + alias4(((helper = (helper = helpers.id || (depth0 != null ? depth0.id : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"id","hash":{},"data":data}) : helper)))
    + "\" data-url=\"/treg/activity/delete?id="
    + alias4(((helper = (helper = helpers.id || (depth0 != null ? depth0.id : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"id","hash":{},"data":data}) : helper)))
    + "\">\r\n                                            <i class=\"glyphicon glyphicon-trash\" style=\"font-size: 20px;\"></i>\r\n                                        </a>\r\n                                    </td>\r\n                                </tr>\r\n                            </table>\r\n                        </div>\r\n                    </div>\r\n                </div>\r\n"
    + ((stack1 = helpers["if"].call(alias1,(depth0 != null ? depth0.description : depth0),{"name":"if","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + "                <div>\r\n                    <p style=\"white-space:pre-line;\">"
    + alias4(((helper = (helper = helpers.description || (depth0 != null ? depth0.description : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"description","hash":{},"data":data}) : helper)))
    + "</p>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div id=\"activity-form-"
    + alias4(((helper = (helper = helpers.id || (depth0 != null ? depth0.id : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"id","hash":{},"data":data}) : helper)))
    + "\" class=\"activity-form\" style=\"display:none\">\r\n            <form>\r\n                <input type=\"hidden\" name=\"activityId\" value=\""
    + alias4(((helper = (helper = helpers.id || (depth0 != null ? depth0.id : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"id","hash":{},"data":data}) : helper)))
    + "\"/>\r\n                <input type=\"hidden\" name=\"date\" value=\"\"/>\r\n                <div  class=\"tablebox\">\r\n                        <div class=\"row\">\r\n                            <div class=\"col-sm-10\">\r\n                                <table>\r\n                                    <tr>\r\n                                        <td>\r\n                                            <select class=\"form-control\" name=\"activityTypeId\">\r\n                                                <option value=\"ARBEID\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,"ARBEID",((stack1 = (depth0 != null ? depth0.activityType : depth0)) != null ? stack1.id : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">Arbeid</option>\r\n                                                <option value=\"AVSPASSERING\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,"AVSPASSERING",((stack1 = (depth0 != null ? depth0.activityType : depth0)) != null ? stack1.id : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">Avspassering</option>\r\n                                                <option value=\"FERIE\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,"FERIE",((stack1 = (depth0 != null ? depth0.activityType : depth0)) != null ? stack1.id : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">Ferie</option>\r\n                                                <option value=\"SYKE_BARN\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,"SYKE_BARN",((stack1 = (depth0 != null ? depth0.activityType : depth0)) != null ? stack1.id : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">Syke barn</option>\r\n                                                <option value=\"SYK_EGENMELDING\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,"SYK_EGENMELDING",((stack1 = (depth0 != null ? depth0.activityType : depth0)) != null ? stack1.id : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">Syk - egenmelding</option>\r\n                                                <option value=\"SYK_SYKEMELDING\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,"SYK_SYKEMELDING",((stack1 = (depth0 != null ? depth0.activityType : depth0)) != null ? stack1.id : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">Syk - sykemelding</option>\r\n                                            </select>\r\n                                        </td>\r\n                                        <td style=\"padding-left:30px;padding-right:5px;\">\r\n                                            <select class=\"form-control\" name=\"hours\">\r\n                                                <option value=\"0\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,0,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">0 timer</option>\r\n                                                <option value=\"1\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,1,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">1 timer</option>\r\n                                                <option value=\"2\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,2,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">2 timer</option>\r\n                                                <option value=\"3\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,3,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">3 timer</option>\r\n                                                <option value=\"4\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,4,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">4 timer</option>\r\n                                                <option value=\"5\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,5,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">5 timer</option>\r\n                                                <option value=\"6\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,6,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">6 timer</option>\r\n                                                <option value=\"7\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,7,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">7 timer</option>\r\n                                                <option value=\"8\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,8,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">8 timer</option>\r\n                                                <option value=\"9\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,9,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">9 timer</option>\r\n                                                <option value=\"10\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,10,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">10 timer</option>\r\n                                                <option value=\"11\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,11,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">11 timer</option>\r\n                                                <option value=\"12\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,12,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">12 timer</option>\r\n                                                <option value=\"13\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,13,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">13 timer</option>\r\n                                                <option value=\"14\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,14,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">14 timer</option>\r\n                                                <option value=\"15\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,15,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">15 timer</option>\r\n                                                <option value=\"16\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,16,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">16 timer</option>\r\n                                                <option value=\"17\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,17,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">17 timer</option>\r\n                                                <option value=\"18\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,18,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">18 timer</option>\r\n                                                <option value=\"19\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,19,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">19 timer</option>\r\n                                                <option value=\"20\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,20,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">20 timer</option>\r\n                                                <option value=\"21\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,21,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">21 timer</option>\r\n                                                <option value=\"22\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,22,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">22 timer</option>\r\n                                                <option value=\"23\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,23,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.hours : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">23 timer</option>\r\n                                            </select>\r\n                                        </td>\r\n                                        <td>\r\n                                            <select class=\"form-control\" name=\"minutes\">\r\n                                                <option value=\"0\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,0,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.minutes : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">0 min</option>\r\n                                                <option value=\"5\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,5,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.minutes : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">5 min</option>\r\n                                                <option value=\"10\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,10,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.minutes : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">10 min</option>\r\n                                                <option value=\"15\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,15,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.minutes : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">15 min</option>\r\n                                                <option value=\"20\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,20,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.minutes : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">20 min</option>\r\n                                                <option value=\"25\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,25,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.minutes : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">25 min</option>\r\n                                                <option value=\"30\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,30,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.minutes : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">30 min</option>\r\n                                                <option value=\"55\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,35,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.minutes : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">35 min</option>\r\n                                                <option value=\"55\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,40,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.minutes : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">40 min</option>\r\n                                                <option value=\"35\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,45,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.minutes : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">45 min</option>\r\n                                                <option value=\"40\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,50,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.minutes : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">50 min</option>\r\n                                                <option value=\"45\""
    + ((stack1 = (helpers.if_eq || (depth0 && depth0.if_eq) || alias2).call(alias1,55,((stack1 = ((stack1 = (depth0 != null ? depth0.time : depth0)) != null ? stack1.hoursMinutes : stack1)) != null ? stack1.minutes : stack1),{"name":"if_eq","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + ">55 min</option>\r\n                                            </select>\r\n                                        </td>\r\n                                    </tr>\r\n                                </table>\r\n                            </div>\r\n                            <div class=\"col-xs-2\">\r\n                                <div class=\"pull-right\">\r\n                                    <a href=\"#\" class=\"cancel-edit-activity\" data-id=\""
    + alias4(((helper = (helper = helpers.id || (depth0 != null ? depth0.id : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"id","hash":{},"data":data}) : helper)))
    + "\" data-url=\"/treg/activity/delete?id="
    + alias4(((helper = (helper = helpers.id || (depth0 != null ? depth0.id : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"id","hash":{},"data":data}) : helper)))
    + "\">\r\n                                        <i class=\"glyphicon glyphicon-remove\" style=\"font-size:20px;\"></i>\r\n                                    </a>\r\n                                </div>\r\n                            </div>\r\n                        </div>\r\n                        <div style=\"margin-top:10px;\">\r\n                            <textarea class=\"form-control\" name=\"description\" rows=\"3\" style=\"white-space:pre-line;resize:vertical;\">"
    + alias4(((helper = (helper = helpers.description || (depth0 != null ? depth0.description : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"description","hash":{},"data":data}) : helper)))
    + "</textarea>\r\n                        </div>\r\n                </div>\r\n                <div class=\"row\">\r\n                    <div class=\"col-sm-12\">\r\n                        <button type=\"button\" class=\"save-activity btn btn-primary\" data-id=\""
    + alias4(((helper = (helper = helpers.id || (depth0 != null ? depth0.id : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"id","hash":{},"data":data}) : helper)))
    + "\" data-url=\"/treg/activity/update\">\r\n                            <span class=\"glyphicon glyphicon-save\"></span> Lagre\r\n                        </button>\r\n                    </div>\r\n                </div>\r\n            </form>\r\n        </div>\r\n    </div>\r\n</div>";
},"useData":true});
templates['attendanceResult'] = template({"1":function(container,depth0,helpers,partials,data) {
    return "";
},"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, alias1=depth0 != null ? depth0 : {}, alias2=helpers.helperMissing;

  return "<div class=\"row\">\r\n    <div class=\"col-sm-12\">\r\n        <div class=\"jumbotron jumbotron-"
    + ((stack1 = (helpers.severity || (depth0 && depth0.severity) || alias2).call(alias1,depth0,{"name":"severity","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + "\">\r\n            <h2><small>Trening 25. juni 2016</small></h2>\r\n            <h1 class=\"jumbotron-header-"
    + ((stack1 = (helpers.severity || (depth0 && depth0.severity) || alias2).call(alias1,depth0,{"name":"severity","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + "\">THE GAME IS ON!</h1>\r\n        </div>\r\n    </div>\r\n</div>\r\n<div class=\"row\">\r\n    <div class=\"col-sm-7\">\r\n        <div class=\"panel panel-default large-box\">\r\n            <div class=\"panel-body\">\r\n                <h3>Kommer du på trening i dag?</h3>\r\n                <form>\r\n                    <div class=\"form-group\">\r\n                        <select class=\"form-control\" style=\"padding:5px;font-size: 120%;\">\r\n                            <option></option>\r\n                            <option>Jeg kommer</option>\r\n                            <option>Jeg kommer ikke</option>\r\n                        </select>\r\n                    </div>\r\n                </form>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div class=\"col-sm-5\">\r\n        <div class=\"panel panel-default large-box\">\r\n            <div class=\"panel-body\">\r\n                <h3>Info</h3>\r\n                <p>\r\n                    Trening hver tirsdag fra kl 20.00 til kl 22.00<br>\r\n                    Stedet er Gaustadhallen<br>\r\n                    Lervikveien 9, 1626 Manstad<br>\r\n                    Pris...<br>\r\n                    <a href=\"#\">Kart</a>\r\n                </p>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n<div class=\"row\">\r\n    <div class=\"col-sm-4\">\r\n        <div class=\"panel panel-default small-box\">\r\n            <div class=\"panel-body\">\r\n                <h3>Kommer <span class=\"badge\">3</span></h3>\r\n                <h4>Steinar</h4>\r\n                <h4>Lars-Petter</h4>\r\n                <h4>Fredrik</h4>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div class=\"col-sm-4\">\r\n        <div class=\"panel panel-default small-box\">\r\n            <div class=\"panel-body\">\r\n                <h3>Kommer ikke <span class=\"badge\">4</span></h3>\r\n                <h4>Steinar</h4>\r\n                <h4>Lars-Petter</h4>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div class=\"col-sm-4\">\r\n        <div class=\"panel panel-default small-box\">\r\n            <div class=\"panel-body\">\r\n                <h3>Ikke svart (4)</h3>\r\n                <h4>Steinar</h4>\r\n                <h4>Lars-Petter</h4>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n";
},"useData":true});
})();